### PR TITLE
Remove old TODO in code by integrating java8 features into codebase

### PR DESCRIPTION
**Pull request by petroseskinder**
There was a TODO statement lingering in the code base. It asked to replace a portion of the code with a java8 one liner. The fix was a simple usage of java8 streams, so I went ahead and included it.

reviewer: @kchodorow 
cc: @hhclam

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Review by kchodorow — APPROVED** [review]

**Comment by kchodorow** [comment]
Jenkins, please test this.

**Comment by kchodorow** [comment]
Okay, well, I have no idea how to set up Jenkins presubmit hooks, unfortunately, so we'll have to wait for @damienmg for that.

**Comment by damienmg** [comment]
@kchodorow: FYI, you did correctly on ci so the only thing that was left is giving the bot the permission to write on the repot so adding the "robot" team to have write permission to the repo.

See https://bazel-review.googlesource.com/c/11890/5/docs/owner.md for an extensive in-progress doc about that.

**Pull request merged**
