### PR TITLE
workaround for bazelbuild/migration-tooling#47

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by vorburger** [comment]
@nevillelyh would you be willing to confirm that you are OK with your commit being contributed by me here?

**Comment by nevillelyh** [comment]
This repo seems to be in an "abandoned" state and we've switched to https://github.com/johnynek/bazel-deps instead.

**Comment by vorburger** [comment]
@nevillelyh oh, really? That's confusing like hell... Let's sort that out over on https://github.com/bazelbuild/migration-tooling/issues/82 ...

**Comment by vorburger** [comment]
Abandon.

**Pull request closed without merging**
