### PR TITLE
Log which maven artifact is currently being resolved

### PR DESCRIPTION
**Pull request by petroseskinder**
Logs whenever an artifact is being resolved in a depth first manner. May contain duplicates since any given package can be depended on by multiple other packages

### CODE REVIEW

**Comment by petroseskinder** [comment]
test for cla

**Comment by petroseskinder** [comment]
test for CLA

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by petroseskinder** [comment]
This was an experimental pull request. Please ignore.

**Pull request closed without merging**
