### PR TITLE
Fix instructions for transitive_maven_jar in README

### PR DESCRIPTION
**Pull request by Hydrotoast**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Review by petroseskinder — APPROVED** [review]
Thank you for the fix. LGTM.
@cgrushko @damienmg

**Comment by damienmg** [comment]
The CLA must be signed before we can import this patch.

**Comment by Hydrotoast** [comment]
I signed it!

**Comment by damienmg** [comment]
Thanks for your contribution!

**Pull request merged**
